[2020-11-25 02:00:49,218] ERROR [apscheduler.executors.default:131] Job "submit_ctrs_records (trigger: cron[hour='*'], next run at: 2020-11-25 03:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/var/www/pacificcontrol.net/apps/training/updater.py", line 26, in submit_ctrs_records
    post_ctrs(session)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 88, in post_ctrs
    if response.json()['status'] == 'OK':
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-11-26 05:56:30,720] ERROR [django.request:224] Internal Server Error: /training/session/264/edit/
Traceback (most recent call last):
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pacificcontrol.net/zhuartcc/decorators.py", line 51, in inner
    return func(request, *args, **kwargs)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 118, in edit_session
    modify_session(session, request)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 48, in modify_session
    session.start = pytz.utc.localize(datetime.fromisoformat(request.POST.get('start')))
ValueError: Invalid isoformat string: '2020-11-26T4:55:00'
[2020-11-26 05:56:30,720] ERROR [django.request:224] Internal Server Error: /training/session/264/edit/
Traceback (most recent call last):
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pacificcontrol.net/zhuartcc/decorators.py", line 51, in inner
    return func(request, *args, **kwargs)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 118, in edit_session
    modify_session(session, request)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 48, in modify_session
    session.start = pytz.utc.localize(datetime.fromisoformat(request.POST.get('start')))
ValueError: Invalid isoformat string: '2020-11-26T4:55:00'
[2020-11-26 15:05:12,841] ERROR [django.security.DisallowedHost:88] Invalid HTTP_HOST header: '/run/gunicorn.sock:'. The domain name provided is not valid according to RFC 1034/1035.
[2020-11-26 15:05:12,841] ERROR [django.security.DisallowedHost:88] Invalid HTTP_HOST header: '/run/gunicorn.sock:'. The domain name provided is not valid according to RFC 1034/1035.
[2020-11-26 16:43:53,446] ERROR [django.request:224] Internal Server Error: /training/session/268/
Traceback (most recent call last):
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pacificcontrol.net/zhuartcc/decorators.py", line 11, in inner
    return func(request, *args, **kwargs)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 38, in view_session
    return render(request, 'session.html', {
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_train_session' not found. 'delete_train_session' is not a valid view function or pattern name.
[2020-11-26 16:43:53,446] ERROR [django.request:224] Internal Server Error: /training/session/268/
Traceback (most recent call last):
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pacificcontrol.net/zhuartcc/decorators.py", line 11, in inner
    return func(request, *args, **kwargs)
  File "/var/www/pacificcontrol.net/apps/training/views.py", line 38, in view_session
    return render(request, 'session.html', {
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/var/www/pacificcontrol.net/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_train_session' not found. 'delete_train_session' is not a valid view function or pattern name.
